kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: default
  name: test-claim
spec:
  storageClassName: efs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: bar
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: efs-pvc
          mountPath: "/data"
      volumes:
      - name: efs-pvc
        persistentVolumeClaim:
          claimName: test-claim